/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "f31af5097d90ef5ae5bd7b8700199bc6189ba34d"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
