/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "1c8089adffdabe3790cc4ca4fb36e24c2f6ab792"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
